language: ruby
rvm:
- 2.2
install: gem install jekyll
script: "[ -e _config_${TRAVIS_BRANCH}.yml ] && jekyll build --config _config_${TRAVIS_BRANCH}.yml || jekyll build"
branches:
  only:
  - master
  - production
  - develop
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch:
    - master
    - production
    - develop
env:
  global:
  - GITHUB_REPO=github.com/rightsstatements/rightsstatements.github.io.git
  - secure: tw9bfGLhUHFYNGXZT7g8eqUQYnDB9Fapg0Vj7mXE7TiX39kHmKbDU3vg9EgdX6kzx/bUVjuPODvDT4rX8SKCTsiJx+NlV6k+M/1X641mvkDU3voW/6EDN2I5ZxRBbJuP0w8zlFA4L4p+1bPjX1LNnt2xLJWG0l34KXaeU2aE9aXn9f/dQqdYJFityU3tEAhBMrI2Gx8W7Sa6K6hnLVFgg9rUNZ7GXriS/4jJsPLdwz7SgxgrSFNKhS8D7OHbGOfYNW0f1e7055797+xYk6bw/90JrTr1lHKCyUA4boWXk+dQyIboH4Ch6VeXjyws+ry1EznI8xLP7LsGWwwZm62PcQ+ja/CdK/rQVDr6ByTFDFXrlxAqeVY7f6Vmb8/dne6wf8JSgCKcBPkrgz3wEjxvY4hWdPOB9g6tnyoajzdvp17Tp9ckqywAkJ+5cLnQtFYZ3OgII53+TnMwCeBiz6s3JTE5lrB+yWfbLk++BWEtNJbsC0uOWL73fES4IgoAF1TvnhyxKbZ2BIVl4+vdc0PXjHXr+KwkPvZD4tPPFK/GeMf2Zwypow5ZFXTE5lk3dxky98Wh743+UhPcbPkVPmSieZJbT+uy0TfMlZtReCkCSFxRtMQZwzJUTqoaDd0odZSLvPvt7Xqi15RTiF4/NQm3uMQSKsgjrpR8ZUwCzY9Qc8g=
  - secure: uiqIhFTXl0vUEhyhVtwNNZxraf8E3torfuAbzudxunX6gkjDobCkvnA2/QVaEfLcekR0p3qshvlAWEBKxFPhV9YnoiRClmSJ8ChGJSnE+Zuw3aax4rjglXjdKEtC/Cz9/Kv4zdTA4GjHdkSnCCRSrKKlJuE6kHa/kQupmgjf4Wsh3sGAPuxVAHXLQ7QNzAuyHLwyXZlBsYYwtneV2EbCS87zSqN9ggR+I7D7jCFj2nbNfS1uoJRKoBkROAXe0Vewj0VntdG9YHt8O5vfE6wjVZQ4Lr9BoLjiW1PccirMRqOk1LgcG6r/U7xZf+XZStQl7Pe0Ww9u3Wbad1XbBVTnIWOcaVuOADf2qzQBiWIB4AKbvH2XTMX3WLAVksQ2iBhsNhskR8GM+dPCGVOQIM8we4ER3qexT35Z1zqai0WmuLzNrVOkh+oM0KMZHR6ByDP4g7+FmPnNk6y8xCgaecq2VUBuYG4dt6le/7UNEZmx051JPlBDjb6CYyExYTAtntws/xELYNLXdCdXRP6BlcAYTVTIxno8uLESboh+AEaGk5u+N912aQeQv2lWvxl4ckhnYuYHanIY0uFK5idyE40JxiJ+7h60enV/wKFmE603CoWm7S9kyhjP1L0bX/1NhlXuwSq4RxpEV4iI+UzPR24KjgJui2S6qhtAcwNVtGlaK/M=
