name: rightsstatements
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: "en"
    values:
      lang: "en"
      iso_name: "English"
default_language: en
languages_enables: no
